### ISSUE TITLE
erreur dans logs serveur

### ISSUE THREAD

**Issue by abenhamdine** [Arhia/payroll-app-next#235]
ERROR 17:20:21 : getSalPeri() : erreur :
2018-07-29T19:20:21+02:00 stack: 'error: column "bul.pad_id" must appear in the GROUP BY clause or be used in an aggregate function\n at Connection.parseE (/home/bas/app_21386476-a451-424c-ad67-870442bbdbe7/node_modules/pg/lib/connection.js:553:11)\n at Connection.parseMessage (/home/bas/app_21386476-a451-424c-ad67-870442bbdbe7/node_modules/pg/lib/connection.js:378:19)\n at Socket.<anonymous> (/home/bas/app_21386476-a451-424c-ad67-870442bbdbe7/node_modules/pg/lib/connection.js:119:22)\n at Socket.emit (events.js:182:13)\n at Socket.EventEmitter.emit (domain.js:442:20)\n at addChunk (_stream_readable.js:283:12)\n at readableAddChunk (_stream_readable.js:264:11)\n at Socket.Readable.push (_stream_readable.js:219:10)\n at TCP.onread (net.js:639:20)',

**Comment by abenhamdine** [comment]
corrigé, en prod dans 10mn
